### PR TITLE
Updating to RN 0.65.1

### PR DESCRIPTION
**Pull request by kanzitelli**

### CODE REVIEW

**Comment by kanzitelli** [comment]
Everything works well, except for the crash on Android causing by RNN (however, works on iOS).

So, now waiting for RNN v8 :)

**Comment by kanzitelli** [comment]
* Now it is working with RNN v7.18.1 (w/ small patch) and [react-native-mmkv](https://github.com/mrousavy/react-native-mmkv) v1.2.5
* Hermes is on
* Flipper initialization for Android is commented for now

**Comment by kanzitelli** [comment]
It crashes on Android when I toggle the theme 2-3 times in the Settings tab and shows this error (from logcat):
`E/libc++abi: terminating with uncaught exception of type std::runtime_error: Unable to retrieve jni environment. Is the thread attached?`

Not sure from which library this is coming, needs more investigation. My first thought was bc of MMKV but I have tried Async Storage and it crashed as well. So maybe it happens because of the RNN's `setDefaultOptions` or `mergeOptions`.

**Comment by Mohamed-kassim** [comment]
@kanzitelli current crash is related to react-native-reanimated compatibility issues with rn65 You can check these issues
[https://github.com/software-mansion/react-native-reanimated/issues/2256#issue-960679169](url)
[https://github.com/software-mansion/react-native-reanimated/issues/2290#issue-973048083](url)

**Comment by Mohamed-kassim** [comment]
#3333

**Comment by kanzitelli** [comment]
Thank you @Mohamed-kassim for the links!

**Comment by kanzitelli** [comment]
I have dig into more and found out that this error
```
E/libc++abi: terminating with uncaught exception of type std::runtime_error: Unable to retrieve jni environment. Is the thread attached?
```
happens when I try to change `key` of a Root component (when changing ui.themeMode) from `utils/designSystem.tsx`-->`withThemeModes()`. Also, when I try to call `Navigation.setRoot()` second time (not sure if I can do that) during an app launch.

**Pull request merged**
